const globals = require("globals");
const babelParser = require("@babel/eslint-parser");
const kaliber = require("@kaliber/eslint-plugin");
const imprt = require("eslint-plugin-import");
const jsxA11y = require("eslint-plugin-jsx-a11y");
const n = require("eslint-plugin-n");
const promise = require("eslint-plugin-promise");
const react = require("eslint-plugin-react");
const reactHooks = require("eslint-plugin-react-hooks");

module.exports = [
  {
    files: ["**/*.js", "**/*.jsx"],
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
          generators: true,
        },
        requireConfigFile: false,
        babelOptions: {
          presets: ["@babel/preset-react"],
        },
      },
      globals: {
        ...globals.browser,
        ...globals.commonjs,
        ...globals.es2022,
        ...globals.jest,
        ...globals.node,
        Component: "readonly",
        React: "readonly",
        cx: "readonly",
      },
    },
    plugins: {
      "@kaliber": kaliber,
      import: imprt,
      "jsx-a11y": jsxA11y,
      n,
      promise,
      react,
      "react-hooks": reactHooks,
    },
    settings: {
      react: {
        version: "detect",
      },
      "import/resolver": {
        "@kaliber/eslint-plugin/lib/absolute-path-resolver-plugin": {
          "path": "./src"
        }
      },
    },
    rules: {
      // http://eslint.org/docs/rules/
      "@kaliber/component-properties": "warn",
      "@kaliber/layout-class-name": "warn",
      "@kaliber/naming-policy": "warn",
      "@kaliber/no-default-export": "warn",
      "@kaliber/no-relative-parent-import": "warn",
      "@kaliber/jsx-key": "warn",

      "brace-style": ["warn", "1tbs", { "allowSingleLine": true }],
      "indent": ["warn", 2, {
        "SwitchCase": 1,
        "flatTernaryExpressions": true
      }],

      "accessor-pairs": "warn",
      "array-callback-return": "warn",
      "arrow-spacing": "warn",
      "block-spacing": "warn",
      "comma-dangle": ["warn", "only-multiline"],
      "comma-spacing": "warn",
      "comma-style": "warn",
      "default-case": ["warn", { "commentPattern": "^no default$" }],
      "dot-location": ["warn", "property"],
      "eol-last": "warn",
      "eqeqeq": "warn",
      "key-spacing": "warn",
      "keyword-spacing": "warn",
      "new-parens": "warn",
      "no-array-constructor": "warn",
      "no-caller": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-delete-var": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extend-native": "warn",
      "no-extra-bind": "warn",
      "no-extra-boolean-cast": "warn",
      "no-extra-label": "warn",
      "no-extra-parens": ["warn", "functions"],
      "no-fallthrough": "warn",
      "no-floating-decimal": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-implied-eval": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-iterator": "warn",
      "no-label-var": "warn",
      "no-labels": ["warn", { "allowLoop": false, "allowSwitch": false }],
      "no-lone-blocks": "warn",
      "no-loop-func": "warn",
      "no-mixed-spaces-and-tabs": "warn",
      "no-proto": "warn",
      "no-return-assign": "warn",
      "no-return-await": "warn",
      "no-trailing-spaces": "warn",
      "no-unneeded-ternary": "warn",
      "no-unsafe-negation": "warn",
      "no-useless-return": "warn",
      "object-curly-spacing": ["warn", "always"],
      "object-shorthand": ["warn", "always"],
      "quotes": ["warn", "single", { "avoidEscape": true, "allowTemplateLiterals": true }],
      "semi": ["warn", "never"],
      "semi-spacing": ["warn", { "before": false, "after": true }],
      "space-before-blocks": "warn",
      "space-before-function-paren": ["warn", { "anonymous": "never", "named": "never", "asyncArrow": "always" }],
      "space-infix-ops": "warn",
      "space-unary-ops": ["warn", { "words": true, "nonwords": false }],
      "template-tag-spacing": "warn",
      "no-mixed-operators": [
        "warn",
        {
          "groups": [
            ["+", "-", "*", "/", "%", "**"],
            ["&", "|", "^", "~", "<<", ">>", ">>>"],
            ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
            ["&&", "||"],
            ["in", "instanceof"],
          ],
          "allowSamePrecedence": false
        },
      ],
      "no-multi-str": "warn",
      "no-native-reassign": "warn",
      "no-negated-in-lhs": "warn",
      "no-new-func": "warn",
      "no-new-object": "warn",
      "no-new-symbol": "warn",
      "no-new-wrappers": "warn",
      "no-obj-calls": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-redeclare": "warn",
      "no-regex-spaces": "warn",
      "no-restricted-globals": ["warn", "addEventListener", "blur", "close", "closed", "confirm", "defaultStatus", "defaultstatus", "event", "external", "find", "focus", "frameElement", "frames", "history", "innerHeight", "innerWidth", "length", "location", "locationbar", "menubar", "moveBy", "moveTo", "name", "onblur", "onwarn", "onfocus", "onload", "onresize", "onunload", "open", "opener", "opera", "outerHeight", "outerWidth", "pageXOffset", "pageYOffset", "parent", "print", "removeEventListener", "resizeBy", "resizeTo", "screen", "screenLeft", "screenTop", "screenX", "screenY", "scroll", "scrollbars", "scrollBy", "scrollTo", "scrollX", "scrollY", "self", "status", "statusbar", "stop", "toolbar", "top"],
      "no-restricted-properties": [
        "warn",
        {
          "object": "require",
          "property": "ensure",
          "message": "Please use import() instead. More info: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#code-splitting"
        },
        {
          "object": "System",
          "property": "import",
          "message": "Please use import() instead. More info: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#code-splitting"
        },
      ],
      "no-restricted-syntax": ["warn", "WithStatement"],
      "no-script-url": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "warn",
      "no-throw-literal": "warn",
      "no-undef": "warn",
      "no-unexpected-multiline": "warn",
      "no-unreachable": "warn",
      "no-unused-expressions": [
        "warn",
        {
          "allowShortCircuit": true,
          "allowTernary": true,
          "allowTaggedTemplates": true
        },
      ],
      "no-unused-labels": "warn",
      "no-unused-vars": [
        "warn",
        {
          "args": "none",
          "ignoreRestSiblings": true
        },
      ],
      "no-use-before-define": [
        "warn",
        {
          "functions": false,
          "classes": false,
          "variables": false
        },
      ],
      "no-useless-computed-key": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-whitespace-before-property": "warn",
      "no-with": "warn",
      "radix": "warn",
      "require-yield": "warn",
      "rest-spread-spacing": ["warn", "never"],
      "strict": ["warn", "never"],
      "unicode-bom": ["warn", "never"],
      "use-isnan": "warn",
      "valid-typeof": "warn",

      "import/first": "warn",
      "import/no-amd": "warn",
      "import/no-webpack-loader-syntax": "warn",
      "import/no-default-export": "off",
      "import/no-duplicates": ["warn", { "considerQueryString": true }],
      "import/export": "warn",
      "import/default": "warn",
      "import/no-unresolved": "warn",
      "import/named": "warn",

      "react/jsx-boolean-value": "warn",
      "react/jsx-curly-spacing": ["warn", "never"],
      "react/jsx-equals-spacing": "warn",
      "react/jsx-indent": ["warn", 2],
      "react/jsx-indent-props": ["warn", 2],
      "react/jsx-key": "off",
      "react/jsx-no-comment-textnodes": "warn",
      "react/jsx-no-duplicate-props": ["warn", { "ignoreCase": true }],
      "react/jsx-no-target-blank": "warn",
      "react/jsx-no-undef": ["warn", { "allowGlobals": true }],
      "react/jsx-pascal-case": ["warn", { "allowAllCaps": true }],
      "react/jsx-tag-spacing": "warn",
      "react/jsx-uses-vars": "warn",
      "react/jsx-wrap-multilines": ["warn", {
        "declaration": "parens-new-line",
        "assignment": "parens-new-line",
        "return": "parens-new-line",
        "arrow": "ignore",
        "condition": "ignore",
        "logical": "ignore",
        "prop": "ignore"
      }],
      "react/no-danger-with-children": "warn",
      "react/no-deprecated": "warn",
      "react/no-direct-mutation-state": "warn",
      "react/no-unused-prop-types": "warn",
      "react/prop-types": ["error", { "skipUndeclared": true }],
      "react/require-render-return": "warn",
      "react/self-closing-comp": "warn",
      "react/void-dom-elements-no-children": "warn",

      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      "jsx-a11y/accessible-emoji": "warn",
      "jsx-a11y/alt-text": "warn",
      "jsx-a11y/anchor-has-content": "warn",
      "jsx-a11y/anchor-is-valid": "warn",
      "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
      "jsx-a11y/aria-props": "warn",
      "jsx-a11y/aria-proptypes": "warn",
      "jsx-a11y/aria-role": "warn",
      "jsx-a11y/aria-unsupported-elements": "warn",
      "jsx-a11y/heading-has-content": "warn",
      "jsx-a11y/html-has-lang": "warn",
      "jsx-a11y/iframe-has-title": "warn",
      "jsx-a11y/img-redundant-alt": "warn",
      "jsx-a11y/no-access-key": "warn",
      "jsx-a11y/no-distracting-elements": "warn",
      "jsx-a11y/no-redundant-roles": "warn",
      "jsx-a11y/role-has-required-aria-props": "warn",
      "jsx-a11y/role-supports-aria-props": "warn",
      "jsx-a11y/scope": "warn",
      "no-path-concat": "warn",
      "react/jsx-uses-react": "off",
      "react/react-in-jsx-scope": "off"
    }
  }
];